export const processIDs = {
  phone_verify: "phone-verify",
  otp_verify: "otp-verify",
  verify_login_token: "verify-login-token",
  user_login_with_phone: "user-login-with-phone",
  user_login_with_email: "user-login-with-email",
  user_email_check: "user-email-check",
  user_phone_check: "user-phone-check",
  create_new_account: "create-new-account",
  update_user: "update-user",
  delete_photo: "delete-photo",
  paytm_transaction_token_generate: "paytm-transaction-token-generate",
  get_all_products: "get-all-products",
  get_product_details: "get-product-details",
  add_item_to_wishlist: "add-item-to-wishlist",
  remove_item_from_wishlist: "remove-item-from-wishlist",
  get_wishlist: "get-wishlist",
};
